#!/usr/bin/env ruby
if !File.exist?('Gemfile.lock')
  puts "No Gemfile.lock found. Run bundle install"
end

require 'bundler'

bundler_paths = Bundler.load.specs.map(&:full_gem_path)
tags_file    = ".tags"
opts         = "--extra=+f -R -f #{tags_file}"
exclude_dirs = "--exclude=.git --exclude=log --exclude=.svn --exclude=bin --exclude=*.json --exclude=tmp --exclude=*.css --exclude=*.js --exclude=*.hpp --exclude=*.h"
ctag_paths   = "* #{bundler_paths.map {|x| x + '/*'}.join(' ')}"
command      = "ctags #{opts} #{exclude_dirs} #{ctag_paths} 2> /dev/null"

puts "Processing ctags..."
system command
puts "Wrote ctags to '#{tags_file}'"
