#
# User configuration sourced by interactive shells
#

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

alias gp="git push"
alias gl="git pull"
alias g="git status"
alias gca="git commit -a"
alias gc="git checkout"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash